# Generated by Django 3.1.4 on 2021-01-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaThesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Название',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('activities', models.TextField(verbose_name='Сфера деятельности')),
                ('login', models.CharField(max_length=150, verbose_name='Логин')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Имена',
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('year_of_issue', models.PositiveSmallIntegerField(default=0, verbose_name='Год выпуска')),
                ('login', models.CharField(max_length=150, verbose_name='Логин')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('id_diploma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.diplomathesis', verbose_name='Диплом')),
            ],
            options={
                'verbose_name': 'Имя',
                'verbose_name_plural': 'Имена',
            },
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('id_employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.employer', verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Названия',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Названия',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('id_employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.employer', verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Названия',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=150, verbose_name='Отчество')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('year_of_issue', models.PositiveSmallIntegerField(default=0, verbose_name='Год выпуска')),
                ('login', models.CharField(max_length=150, verbose_name='Логин')),
                ('password', models.CharField(max_length=150, verbose_name='Пароль')),
                ('id_profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.profession', verbose_name='Профессия')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('target', models.TextField(verbose_name='Цель')),
                ('experience', models.TextField(verbose_name='Опыт')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('id_graduate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.graduate', verbose_name='Образование, степень')),
                ('id_vacancy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.vacancies', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Названия',
            },
        ),
        migrations.CreateModel(
            name='RequestForPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_practice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.practice', verbose_name='Практика')),
                ('id_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.students', verbose_name='Студент')),
            ],
        ),
        migrations.AddField(
            model_name='graduate',
            name='id_profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.profession', verbose_name='Профессия'),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('id_employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.employer', verbose_name='Работодатель')),
            ],
            options={
                'verbose_name': 'Название',
                'verbose_name_plural': 'Названия',
            },
        ),
    ]
