# Generated by Django 3.1.4 on 2021-01-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diplomathesis',
            options={'verbose_name': 'Диплом', 'verbose_name_plural': 'Данные о дипломе'},
        ),
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Работодатель', 'verbose_name_plural': 'Работодатели'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='graduate',
            options={'verbose_name': 'Выпускник', 'verbose_name_plural': 'Выпускники'},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'verbose_name': 'Практика', 'verbose_name_plural': 'Данные о практиках'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'Профессия', 'verbose_name_plural': 'Профессии'},
        ),
        migrations.AlterModelOptions(
            name='requestforpractice',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки на практику'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='vacancies',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='vacancies',
            name='image',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
