# Generated by Django 3.1.4 on 2021-01-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_auto_20210105_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancies',
            options={},
        ),
        migrations.AlterModelTable(
            name='vacancies',
            table='Вакансии',
        ),
    ]
