# Generated by Django 3.1.4 on 2021-01-08 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_auto_20210107_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='requirements',
            field=models.TextField(null=True, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id_graduate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.graduate', verbose_name='Выпускник'),
        ),
    ]
