# Generated by Django 3.1.5 on 2021-01-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_auto_20210108_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
    ]
