# Generated by Django 3.1.4 on 2021-01-12 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0006_auto_20210112_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='end',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='practice',
            name='start',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата начала'),
        ),
    ]
